#Jalon 2 : Vectorisation et mod√©lisation

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import nltk

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
DATASET_FILE = "/content/drive/MyDrive/IAA2/Sitou/dataset_cleaned.csv"

In [4]:
dataset_cleaned = pd.read_csv(DATASET_FILE)
dataset_cleaned_text=dataset_cleaned["text_cleaned"]
neg_reviews=dataset_cleaned_text[dataset_cleaned.stars.isin([1,2])]

## Vectorisation

In [5]:
#Vectorisation avec tf-idf

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer( max_df=0.6, min_df=0.008) #On a environ 1000 mots uniques pour 10000 reviews
tf_idf = vectorizer.fit_transform(neg_reviews)
array=vectorizer.get_feature_names_out()
print(array)
print(tf_idf)

['00' '10' '100' ... 'yet' 'young' 'zero']
  (0, 808)	0.18501150559794655
  (0, 683)	0.10659751783099351
  (0, 995)	0.15680955638497224
  (0, 201)	0.2033522121611107
  (0, 48)	0.2083098991034262
  (0, 279)	0.15175920311815977
  (0, 911)	0.5613531661653862
  (0, 654)	0.23797493778733883
  (0, 149)	0.23461383636119912
  (0, 895)	0.23725787872618426
  (0, 990)	0.1713940540710003
  (0, 630)	0.21712700151363146
  (0, 465)	0.23118679023989078
  (0, 902)	0.16016018083219188
  (0, 482)	0.11915612982197485
  (0, 349)	0.21154586126551414
  (0, 226)	0.30231069077475836
  (0, 354)	0.18165302394355035
  (1, 261)	0.2209845034581554
  (1, 155)	0.24062771740417416
  (1, 233)	0.20482645321657023
  (1, 716)	0.1998232460996296
  (1, 632)	0.19458656702904878
  (1, 793)	0.10816069991305825
  (1, 624)	0.15118244041384163
  :	:
  (9998, 711)	0.141355335716276
  (9998, 395)	0.2012721076572345
  (9998, 781)	0.15757906075076947
  (9998, 107)	0.163775307455832
  (9998, 934)	0.16892522859693887
  (9998, 383)	0.08318385065539066
  (9998, 990)	0.2658319916989207
  (9998, 354)	0.07043591070703338
  (9999, 239)	0.2601837585433214
  (9999, 543)	0.26857243293831773
  (9999, 234)	0.22659507506297197
  (9999, 799)	0.22670180942496623
  (9999, 98)	0.2755854337033914
  (9999, 159)	0.2364525534850849
  (9999, 471)	0.2221822316613364
  (9999, 464)	0.16646099212691334
  (9999, 527)	0.362036676676267
  (9999, 924)	0.24633389954508533
  (9999, 917)	0.16608475054982935
  (9999, 343)	0.16888924319198825
  (9999, 80)	0.13176311359355408
  (9999, 433)	0.20712743269901554
  (9999, 795)	0.28770411434865845
  (9999, 186)	0.38573045320342386
  (9999, 354)	0.09391100443750496

In [6]:
#Conversion tf_idf en matrice
matrice_tfidf=pd.DataFrame(tf_idf.toarray(),columns=array)
matrice_tfidf

,00,10,100,11,12,14,15,16,18,20,...,wrong,yeah,year,yell,yelp,yes,yesterday,yet,young,zero
0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.392054,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.449125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9996,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9997,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
#NMF
from sklearn.decomposition import NMF
nmf_model = NMF(n_components=15, init='random', random_state=0)
W = nmf_model.fit_transform(tf_idf) # matrice documentsxtopics 
H = nmf_model.components_ # matrice topicsxdocuments
print(W)
print(H)

[[0.         0.26289463 0.         ... 0.         0.00441175 0.        ]
 [0.07399771 0.         0.00511009 ... 0.00466011 0.         0.0537856 ]
 [0.14470968 0.10628558 0.03176195 ... 0.         0.         0.        ]
 ...
 [0.14345838 0.         0.11904968 ... 0.         0.00043016 0.        ]
 [0.         0.06615615 0.07986371 ... 0.07651574 0.         0.        ]
 [0.10824379 0.04884539 0.03567646 ... 0.         0.         0.        ]]
[[1.66649931e-05 4.23853377e-02 5.16088415e-03 ... 1.53445076e-02
  5.52726998e-03 0.00000000e+00]
 [1.84005648e-03 0.00000000e+00 3.74587865e-03 ... 9.08933226e-03
  0.00000000e+00 5.44937393e-03]
 [1.59854811e-02 0.00000000e+00 0.00000000e+00 ... 1.00555703e-03
  1.17804820e-03 0.00000000e+00]
 ...
 [2.76512601e-02 2.31619729e-02 0.00000000e+00 ... 4.49129324e-04
  0.00000000e+00 0.00000000e+00]
 [4.47476655e-03 0.00000000e+00 0.00000000e+00 ... 3.65957176e-03
  4.94474618e-03 0.00000000e+00]
 [5.13088790e-04 2.01918244e-01 0.00000000e+00 ... 1.45305606e-02
  0.00000000e+00 2.09080475e-03]]

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:1641: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  ConvergenceWarning,

In [8]:
matrice_doctopic=pd.DataFrame(W)
matrice_doctopic

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.000000,0.262895,0.000000,0.000000,0.000000,0.128743,0.000000,0.000000,0.000000,0.041751,0.000000,0.000000,0.000000,0.004412,0.000000
1,0.073998,0.000000,0.005110,0.000000,0.000000,0.000000,0.005729,0.000811,0.000000,0.000000,0.058987,0.000000,0.004660,0.000000,0.053786
2,0.144710,0.106286,0.031762,0.013234,0.000000,0.054293,0.000000,0.001775,0.000000,0.000000,0.033251,0.116995,0.000000,0.000000,0.000000
3,0.072571,0.174529,0.072438,0.022300,0.001370,0.000000,0.000000,0.000000,0.000000,0.042097,0.010626,0.000000,0.000080,0.003025,0.000000
4,0.000000,0.000000,0.044849,0.000000,0.000000,0.058364,0.000000,0.000000,0.098112,0.049306,0.000000,0.004095,0.006626,0.000000,0.029825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.000000,0.126501,0.020539,0.000000,0.001208,0.000000,0.000000,0.000000,0.006097,0.000000,0.000000,0.000000,0.007493,0.000541,0.000000
9996,0.008151,0.136026,0.049403,0.023156,0.123723,0.001354,0.000000,0.010330,0.016325,0.079329,0.026551,0.013364,0.092878,0.005039,0.000000
9997,0.143458,0.000000,0.119050,0.000000,0.000000,0.085874,0.000000,0.362131,0.061720,0.000000,0.075873,0.000000,0.000000,0.000430,0.000000
9998,0.000000,0.066156,0.079864,0.005285,0.020622,0.059303,0.000000,0.006705,0.000000,0.001905,0.000000,0.004047,0.076516,0.000000,0.000000
9999,0.108244,0.048845,0.035676,0.196850,0.000000,0.066457,0.000000,0.000000,0.010182,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [9]:
matrice_topicdoc=pd.DataFrame(H)
matrice_topicdoc

,0,1,2,3,4,5,6,7,8,9,...,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031
0,0.000017,0.042385,0.005161,0.001440,0.007767,0.008100,0.028240,0.001910,0.006303,0.015875,...,0.000000,0.008912,0.000000,0.000116,0.000000,0.013146,0.000337,0.015345,0.005527,0.000000
1,0.001840,0.000000,0.003746,0.000000,0.006132,0.003035,0.000000,0.003500,0.003880,0.000000,...,0.000000,0.004046,0.008798,0.000000,0.018757,0.004384,0.000000,0.009089,0.000000,0.005449
2,0.015985,0.000000,0.000000,0.004475,0.010413,0.005259,0.000000,0.009201,0.009338,0.000000,...,0.000000,0.000818,0.008710,0.000000,0.000000,0.004397,0.000000,0.001006,0.001178,0.000000
3,0.005512,0.008322,0.002068,0.003413,0.000784,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000525,0.000000,0.187905,0.000000,0.000000,0.000000,0.019034,0.006163,0.000000,0.000000
4,0.000000,0.000000,0.003499,0.007965,0.000000,0.004914,0.000000,0.001231,0.011323,0.000889,...,0.000000,0.006166,0.003436,0.000000,0.000000,0.000000,0.000906,0.014367,0.003209,0.003734
5,0.000000,0.000000,0.007400,0.000000,0.002793,0.000000,0.000000,0.000000,0.002529,0.001503,...,0.000000,0.001864,0.000000,0.006663,0.000000,0.000000,0.005502,0.003179,0.000000,0.000000
6,0.000000,0.000000,0.001421,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.006242,...,0.019975,0.000000,0.000000,0.003873,0.005325,0.000000,0.000000,0.019342,0.000000,0.029531
7,0.000000,0.004708,0.001947,0.005721,0.004448,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.007188,0.000000,0.000000,0.009090,0.004626,0.010181,0.000000,0.000000,0.000000
8,0.003352,0.041726,0.000000,0.010583,0.001280,0.003600,0.033787,0.005751,0.000000,0.044806,...,0.202315,0.002777,0.000000,0.000005,0.000000,0.000000,0.000115,0.007476,0.000000,0.000000
9,0.000000,0.017361,0.010015,0.011758,0.008738,0.000000,0.000000,0.000000,0.000000,0.002450,...,0.036814,0.013645,0.068328,0.007635,0.055203,0.015612,0.000000,0.015856,0.002842,0.020493
10,0.053391,0.056579,0.016166,0.034497,0.019591,0.005388,0.022563,0.006879,0.022152,0.044146,...,0.033095,0.019039,0.027395,0.056249,0.057183,0.070004,0.027432,0.038678,0.080988,0.041407
11,0.000000,0.020579,0.000516,0.000000,0.015533,0.005114,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000776,0.000000,0.000000,0.000000,0.012679,0.000000,0.000000,0.000000,0.000000
12,0.027651,0.023162,0.000000,0.005594,0.020087,0.006929,0.000000,0.014630,0.000000,0.006764,...,0.009466,0.000000,0.000000,0.000000,0.000000,0.000000,0.004855,0.000449,0.000000,0.000000
13,0.004475,0.000000,0.000000,0.007203,0.004608,0.007362,0.000000,0.008861,0.000000,0.000000,...,0.012916,0.005238,0.000000,0.000000,0.000000,0.008355,0.009209,0.003660,0.004945,0.000000
14,0.000513,0.201918,0.000000,0.016863,0.016176,0.002706,0.245549,0.001376,0.000000,0.222452,...,0.000000,0.000000,0.000000,0.000000,0.004598,0.005384,0.000000,0.014531,0.000000,0.002091

In [10]:
#Affichage des topics
def display_topics(model, feature_names, num_top_words,topic_names=None):
    for ix, topic in enumerate(model.components_):
        #print topic, topic number, and top words
        if not topic_names or not topic_names[ix]:
            print("\nTopic ", ix)
        else:
            print("\nTopic: '",topic_names[ix],"'")
        print(", ".join([feature_names[i] \
             for i in topic.argsort()[:-num_top_words - 1:-1]]))

In [11]:
#Affichage des mots corr√©l√©s aux diff√©rents topics

nmf_model = NMF(15)
doc_topic = nmf_model.fit_transform(tf_idf)
display_topics(nmf_model, vectorizer.get_feature_names(), 5)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,

Topic  0
say, tell, customer, would, call

Topic  1
good, taste, like, dish, sauce

Topic  2
pizza, crust, cheese, topping, slice

Topic  3
order, take, delivery, get, wrong

Topic  4
food, service, bad, slow, good

Topic  5
table, come, server, waitress, ask

Topic  6
burger, fry, bun, onion, good

Topic  7
wait, minute, hour, 30, 15

Topic  8
chicken, rice, fry, wing, dry

Topic  9
bar, drink, beer, bartender, night

Topic  10
time, go, last, first, location

Topic  11
coffee, breakfast, egg, staff, cup

Topic  12
sandwich, salad, cheese, bread, lettuce

Topic  13
sushi, roll, fish, rice, salmon

Topic  14
place, like, really, get, go

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [12]:
#Liste des diff√©rents topics

LISTE_TOPIC = {'0':'Esth√©tique du cadre',
              '1':'Qualit√© de la sauce',
              '2':'Qualit√© de la pizza',
              '3':'Qualit√© du service au niveau de la prise de commande',
              '4':'Rapidit√© du sercive',
              '5':'Staff du restaurant',
              '6':'Description des burgers',
              '7':"Temps d'attente",
              '8':"Menu poulet",
              '9':"Boissons disponibles au bar",
              '10':"Comparaison par rapport √† un autre passage dans le restaurant",
              '11':"Plainte des clients au manager",
              '12':"Garniture sandwich",
              '13':"Menu sushi",
              '14':"Probabilit√© de revenir dans le restaurant"}

LISTE_TOPIC

{'0': 'Esth√©tique du cadre',
 '1': 'Qualit√© de la sauce',
 '2': 'Qualit√© de la pizza',
 '3': 'Qualit√© du service au niveau de la prise de commande',
 '4': 'Rapidit√© du sercive',
 '5': 'Staff du restaurant',
 '6': 'Description des burgers',
 '7': "Temps d'attente",
 '8': 'Menu poulet',
 '9': 'Boissons disponibles au bar',
 '10': 'Comparaison par rapport √† un autre passage dans le restaurant',
 '11': 'Plainte des clients au manager',
 '12': 'Garniture sandwich',
 '13': 'Menu sushi',
 '14': 'Probabilit√© de revenir dans le restaurant'}

In [39]:
#Affichage des reviews les plus pertinentes pour chaque topic

matrice_doctopic.columns=['Esth√©tique du cadre','Qualit√© de la sauce','Qualit√© de la pizza','Qualit√© du service au niveau de la prise de commande','Rapidit√© du sercive',
                          'Staff du restaurant','Description des burgers',"Temps d'attente","Menu poulet","Boissons disponibles au bar",
                          "Comparaison par rapport √† un autre passage dans le restaurant","Plainte des clients au manager",
                            "Garniture sandwich","Menu sushi","Probabilit√© de revenir dans le restaurant"]

                              

matrice_doctopic

,Esth√©tique du cadre,Qualit√© de la sauce,Qualit√© de la pizza,Qualit√© du service au niveau de la prise de commande,Rapidit√© du sercive,Staff du restaurant,Description des burgers,Temps d'attente,Menu poulet,Boissons disponibles au bar,Comparaison par rapport √† un autre passage dans le restaurant,Plainte des clients au manager,Garniture sandwich,Menu sushi,Probabilit√© de revenir dans le restaurant
0,0.000000,0.262895,0.000000,0.000000,0.000000,0.128743,0.000000,0.000000,0.000000,0.041751,0.000000,0.000000,0.000000,0.004412,0.000000
1,0.073998,0.000000,0.005110,0.000000,0.000000,0.000000,0.005729,0.000811,0.000000,0.000000,0.058987,0.000000,0.004660,0.000000,0.053786
2,0.144710,0.106286,0.031762,0.013234,0.000000,0.054293,0.000000,0.001775,0.000000,0.000000,0.033251,0.116995,0.000000,0.000000,0.000000
3,0.072571,0.174529,0.072438,0.022300,0.001370,0.000000,0.000000,0.000000,0.000000,0.042097,0.010626,0.000000,0.000080,0.003025,0.000000
4,0.000000,0.000000,0.044849,0.000000,0.000000,0.058364,0.000000,0.000000,0.098112,0.049306,0.000000,0.004095,0.006626,0.000000,0.029825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.000000,0.126501,0.020539,0.000000,0.001208,0.000000,0.000000,0.000000,0.006097,0.000000,0.000000,0.000000,0.007493,0.000541,0.000000
9996,0.008151,0.136026,0.049403,0.023156,0.123723,0.001354,0.000000,0.010330,0.016325,0.079329,0.026551,0.013364,0.092878,0.005039,0.000000
9997,0.143458,0.000000,0.119050,0.000000,0.000000,0.085874,0.000000,0.362131,0.061720,0.000000,0.075873,0.000000,0.000000,0.000430,0.000000
9998,0.000000,0.066156,0.079864,0.005285,0.020622,0.059303,0.000000,0.006705,0.000000,0.001905,0.000000,0.004047,0.076516,0.000000,0.000000
9999,0.108244,0.048845,0.035676,0.196850,0.000000,0.066457,0.000000,0.000000,0.010182,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [38]:
print("Les review les plus pertinentes sont:")

print("Topic n¬∞1 : review num√©ro  ",matrice_doctopic['Esth√©tique du cadre'].argmax())
print("Topic n¬∞2 : review num√©ro  ",matrice_doctopic['Qualit√© de la sauce'].argmax())
print("Topic n¬∞3 : review num√©ro  ",matrice_doctopic['Qualit√© de la pizza'].argmax())
print("Topic n¬∞4 : review num√©ro  ",matrice_doctopic['Qualit√© du service au niveau de la prise de commande'].argmax())
print("Topic n¬∞5 : review num√©ro  ",matrice_doctopic['Staff du restaurant'].argmax())
print("Topic n¬∞6 : review num√©ro  ",matrice_doctopic['Description des burgers'].argmax())
print("Topic n¬∞7 : review num√©ro  ",matrice_doctopic["Temps d'attente"].argmax())
print("Topic n¬∞8 : review num√©ro  ",matrice_doctopic['Menu poulet'].argmax())
print("Topic n¬∞9 : review num√©ro  ",matrice_doctopic['Boissons disponibles au bar'].argmax())
print("Topic n¬∞10 : review num√©ro  ",matrice_doctopic['Comparaison par rapport √† un autre passage dans le restaurant'].argmax())
print("Topic n¬∞11 : review num√©ro  ",matrice_doctopic['Plainte des clients au manager'].argmax())
print("Topic n¬∞12 : review num√©ro  ",matrice_doctopic['Garniture sandwich'].argmax())
print("Topic n¬∞13 : review num√©ro  ",matrice_doctopic['Menu sushi'].argmax())
print("Topic n¬∞14: review num√©ro  ",matrice_doctopic['Probabilit√© de revenir dans le restaurant'].argmax())

Les review les plus pertinentes sont:
Topic n¬∞1 : review num√©ro   4765
Topic n¬∞2 : review num√©ro   8368
Topic n¬∞3 : review num√©ro   7520
Topic n¬∞4 : review num√©ro   1691
Topic n¬∞5 : review num√©ro   8377
Topic n¬∞6 : review num√©ro   1698
Topic n¬∞7 : review num√©ro   5222
Topic n¬∞8 : review num√©ro   6369
Topic n¬∞9 : review num√©ro   2490
Topic n¬∞10 : review num√©ro   1510
Topic n¬∞11 : review num√©ro   9130
Topic n¬∞12 : review num√©ro   6384
Topic n¬∞13 : review num√©ro   6270
Topic n¬∞14: review num√©ro   4098

In [22]:
#Cr√©ation des fichiers pickle
import pickle

file_name='nmf_model2.pkl'
f = open(file_name,'wb')
pickle.dump(W,f)
f.close()

In [14]:
import pickle

file_name='vectorizer.pkl'
f = open(file_name,'wb')
pickle.dump(vectorizer ,f)
f.close()